### ISSUE TITLE
Update to 1.7.X?

### ISSUE THREAD

**Issue by Blue64** [bdew-minecraft/eumfr#1]
I was wondering if this already got worked into 1.7.X somewhere? Ender Lilies do tend to take nearly forever, so it'd be nice to be able to automate them, and auto fertilize them too. If this isn't yet worked into 1.7.X, that'd be super awesome and useful. 1.7.10 gave me a NoSuchMethod error and pointed to [here](https://github.com/bdew/eumfr/blob/master/src/net/bdew/eu_mfr/EuMfrIntegration.scala#L31) (specifically `.getModLog`)

I'd do it myself, but I know nothing about scala, I barely recall any Eclipse JavaScript, and I've got zero clue how 1.6.X works compared to 1.7.X (nor do I know how 1.7.X works), plus I don't know if it's already been done.

**Comment by bdew** [comment]
It was integrated into Extra Utilities at some point, should work without any additional mods in modern versions.
